-- AlterTable
ALTER TABLE "Wedding" ADD COLUMN "coverImagePosX" DOUBLE PRECISION NOT NULL DEFAULT 50;
ALTER TABLE "Wedding" ADD COLUMN "coverImagePosY" DOUBLE PRECISION NOT NULL DEFAULT 50;
ALTER TABLE "Wedding" ADD COLUMN "coverImageScale" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "Wedding" ADD COLUMN "titleFontScale" DOUBLE PRECISION NOT NULL DEFAULT 1;
